# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iloilo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inherit! :search_paths
  # Pods for iloilo

  target 'iloiloTests' do
    project 'iloilo'
    pod "Quick"
    pod "EarlGrey"
  end
end

